version: "3.8"
services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
  redis:
    image: redis:latest
    ports:
      - "6379:6379" 
    volumes:
      - redis-data:/data
    command: redis-server
    restart: always
volumes:
  pgdata:
  redis-data:
