version: "3.9"  # Specify a Docker Compose version

services:
  postgres:
    image: postgres:14
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: example
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    command: redis-server
    restart: always

  mongodb:
    image: mongo:latest  # Use 'mongo' instead of 'mongodb-community-server'
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root  # Use correct environment variable names
      MONGO_INITDB_ROOT_PASSWORD: example
      MONGO_INITDB_DATABASE: mushroom
    volumes:
      - mongodb-data:/data/db  # Mount to the correct data directory

volumes:
  pgdata:
  redis-data:
  mongodb-data:
